web:
  image: nginx
  volumes:
    - ./conf/badconfig.template:/etc/nginx/conf.d/badconfig.template
    - ./html:/var/www
  ports:
    - "8080:80"
    - "8081:81"
  environment:
    - ROOT=/var/www/
  command: /bin/sh -c "envsubst '$$ROOT' < /etc/nginx/conf.d/badconfig.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
